#%RAML 1.0 NamedExample
value:
 
  -
    ID: 0
    firstname: Max
    lastname: Madden
    email: max@gmail.com
    telephone: 621 557 887
    
  -
    ID: 0
    firstname: Anita
    lastname: Kukac
    email: anita@gmail.com
    telephone: 621 326 237